# fly.toml app configuration file generated for powerflow on 2026-05-10T12:47:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'powerflow'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  ASPNETCORE_HTTPS_REDIRECTION = 'false'
  ASPNETCORE_URLS = 'http://+:8080'


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 200
    soft_limit = 100

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '15s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
